### PR TITLE
[eclipse/xtext#1653] workaround fix for check versions

### PR DESCRIPTION
**Pull request by cdietrich**
[eclipse/xtext#1653] workaround fix for check versions
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

please note: this is just a fix and not a cleanup task

### CODE REVIEW

**Comment by kthoms** [comment]
I have set up a job that takes your branch for testing https://ci.eclipse.org/xtext/job/releng/job/check-versions-dev

**Comment by kthoms** [comment]
Does what I'd expect

screenshot 384

**Review by kthoms — APPROVED** [review]

**Comment by cdietrich** [comment]
@kthoms you can delete the branch again.
i already had tested with the master job

**Comment by kthoms** [comment]
Done

**Comment by kthoms** [comment]
You mean to delete the job, right?

**Comment by cdietrich** [comment]
yes your experimental job

**Pull request merged**
